### ISSUE TITLE
Hide details behind --verbose flag

### ISSUE THREAD

**Issue by henno** [bitalizer/db-migrator#10]
Only display verbose details such as executed queries and created table definitions when the --verbose flag is active. If this flag is not present, the program should only present a high-level overview of its progress. This overview will allow users to quickly identify the program's version and any warnings, making clear which tables are processed.

**Comment by bitalizer** [comment]
https://github.com/bitalizer/db-migrator/commit/023bf1f4ab37cf77dd7d35e816764c05141eee93
