### ISSUE TITLE
Parallel processing of tables

### ISSUE THREAD

**Issue by henno** [bitalizer/db-migrator#5]
It would be good if all the tables would be processed in parallel while taking into account the number of threads in the computer.

**Comment by henno** [comment]
Should be an optional feature to be able to prevent potential disruption by hardware resource saturation for multipurpose servers with live users.

**Comment by henno** [comment]
Or an option to control the level of parallelism like how many tables are processed in parallel.

**Comment by bitalizer** [comment]
https://github.com/bitalizer/db-migrator/commit/4ed57edeecd9c6ef1410e2760da1881eeb90b408
